---
title: "Volcono RMarkdown"
author: "Adebola Agboola"
date: "2024-02-22"
output: html_document
---
#Set the working directory.
```{r}

setwd("/cloud/project/SURP_RPlots-master")
```

#Load the libraries
```{r}
library(ggplot2)
library(gplots)

```

#Read gene file
```{r}
gene.transcript=read.csv("gene.description_sub.csv")

```

#Analyze data in gene file
```{r}
#Check how many dimensions the dataset has (rows and columns)
dim(gene.transcript)

# Check what the column names are of your data
colnames(gene.transcript)

# Also check what class of data you are using
class(gene.transcript)

```

#Plot the volcano with label and legend
```{r}
# Plot your volcano plot first 
# including labeling red the genes that exceed an adjusted p-value of 0.05
plot(x = gene.transcript$log2FoldChange.L8_DOXvsL8., 
     y = -log10(gene.transcript$pvalue.L8_DOXvsL8.), 
     las = 1, 
     xlim = c(-4,4),
     ylim = c(0,200),
     col = ifelse(gene.transcript$padj.L8_DOXvsL8<=0.05, "red", "black"),
     xlab = "log2 Fold Change",
     ylab = "-log10(p-value)",
     main = "Volcano Plot of L8")
# Then add your labels to your plot only for genes whos
# adjusted p-values that are less than or equal to 0.05 
# AND 
# log2 fold change that is 1.5 in the positive or negative direction (or 2 -- 
text(x = gene.transcript$log2FoldChange.L8_DOXvsL8., 
     y = -log10(gene.transcript$pvalue.L8_DOXvsL8.), 
     labels = ifelse(gene.transcript$padj.L8_DOXvsL8. <= 0.05 & abs(gene.transcript$log2FoldChange.L8_DOXvsL8.) >= 1.5, 
                     as.vector(gene.transcript$GeneName), NA),
     cex = 0.5, pos = 3)

#Add Label
# Then add your legend! 
# (It doesn't matter which order you do the text/legend)
legend("topright", 
       legend = c("significant"), 
       pt.bg = c("red"), 
       bty = "n",
       pch = 21, 
       cex = 0.8)
```


